### ISSUE TITLE
Error 3044

### ISSUE THREAD

**Issue by lisasmcdurham** [bamiesking/st-margaret#2]
Linked fe to be as described in the wiki, got a new error on clicking to generate new record:

![image](https://user-images.githubusercontent.com/68745176/90400992-3d373a80-e095-11ea-8742-f29126e42583.png)

Looked at the Linked Table Manager and some of them are still linked to your drive, though I clicked 'select all' when linking the back end:

![image](https://user-images.githubusercontent.com/68745176/90401149-75d71400-e095-11ea-8394-f84e76ace865.png)

Went through the steps again to link fe to be so you can see the linked tables, below. I did 'select all' but not all the ones seen in the error pop-up were there. Wondering if it is something to do with that?

![image](https://user-images.githubusercontent.com/68745176/90401263-999a5a00-e095-11ea-8652-08f7ef55648c.png)

**Comment by bamiesking** [comment]
Hi, I think the issue here is that you haven't unlinked the existing tables before adding new ones, which means that the names of the new ones have a 1 appended to them and so the database front-end still tries to access the back-end on my file system. To fix this, I have just uploaded a new release (v0.1.1) which should fix this - I have simply unlinked the tables before zipping the front-end

**Comment by lisasmcdurham** [comment]
Hi, yes that worked thank you. I tried again on my own computer and was able to open up the create new record page!

**Comment by bamiesking** [comment]
It looks like a fresh download has fixed #1 and fixed #2 too. I'll close these issues.
